language: cpp
matrix:
  include:
    # works on Precise and Trusty
    - os: linux
      addons:
        apt:
          sources:
            - ubuntu-toolchain-r-test
            - george-edison55-precise-backports
          packages:
            - /scratch/nvm/benchmarks/RECIPE/g++
            - cmake-data
            - cmake
            - lcov
            - libtcmalloc-minimal4
            - libtcmalloc-minimal4-dbg
            - libgoogle-perftools-dev
      env:
        - COMPILER=/scratch/nvm/benchmarks/RECIPE/g++
        - MATRIX_EVAL="CC=/scratch/nvm/benchmarks/RECIPE/gcc && CXX=/scratch/nvm/benchmarks/RECIPE/g++ && GCOV=gcov-7"

before_install:
    - eval "${MATRIX_EVAL}"

install:
  - sudo update-alternatives --install /usr/bin/gcov gcov /usr/bin/gcov-7 90
  - sudo update-alternatives --install /usr/bin/g++ g++ /usr/bin/g++-7 90
  - sudo update-alternatives --install /usr/bin/gcc gcc /usr/bin/gcc-7 90

compiler:
  - gcc
script:
  ./runTests.sh -DUSETRAVIS=ON
after_success:
  - bash <(curl -s https://codecov.io/bash) -f coverageReport/libraries_coverage.info
